apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csv-pv-claim
  namespace: {{ .Values.namespace }}
spec:
  storageClassName: csv-path
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi